### ISSUE TITLE
假如我对Mist处理后的图片进行有损压缩，mist的水印是否还能生效

### ISSUE THREAD

**Issue by Kuriboh2017** [mist-project/mist-v2#11]

**Comment by sakukaze-rin** [comment]
![image](https://github.com/mist-project/mist-v2/assets/119785537/2b5ee6cd-6f3a-424f-85b4-41f9f6b078b7)
[(https://mist-project.github.io/index.html)]
从官方说明文档上来看，是这样的

**Comment by caradryanl** [comment]
It depends on the strength of Mist and the strength of compression. 
取决于你加的Mist的强度和有损压缩的强度。
