### ISSUE TITLE
What do different attack modes of the command line parameter --mode represent in terms of algorithms?

### ISSUE THREAD

**Issue by jyweky** [mist-project/mist-v2#19]
I'd like to ask about the correspondence between the command line parameters --mode ['lunet', 'fused', 'anti-db'] and the attack algorithms in the paper. I assume 'lunet' corresponds to ITA or ITA+, 'anti-db' directly corresponds to ANTI-DB. However, what does 'fused' represent?

**Comment by caradryanl** [comment]
Fused means ITA+
