### ISSUE TITLE
lora does not work?

### ISSUE THREAD

**Issue by lunaryan** [mist-project/mist-v2#22]
Dear authors,

I am applying the code on the wikiart dataset. I set the argument as:

accelerate launch attacks/mist.py --cuda --low_vram_mode --instance_data_dir /data4/user/yan390/diffusion/Impress/processed_wikiart/$artist/clean/train --output_dir output_$artist --class_data_dir data/class --instance_prompt "a misted art work by artist $artist" --class_prompt "an art work by artist $artist" --mixed_precision bf16 -p "stable-diffusion-2-1-base"

and followed by:
accelerate launch eval/train_dreambooth_lora_15.py --instance_data_dir=output_$artist --output_dir=lora_$artist --class_data_dir=lora_class_dir --instance_prompt "a misted artwork by artist $artist" --class_prompt "an artwork by artist $artist" --resolution=512 --train_batch_size=1 --learning_rate=1e-4 --scale_lr --max_train_steps=2000 --pretrained_model_name_or_path stable-diffusion-2-1-base.

So I got a lora using clean data and another using misted images.
However, I found they both generate the exact same images using sample_lora_15.py. The misted images seem produced correctly since the finetuned SD model using misted images generate new images with the adversarial pattern. However, they just seem do not make a difference when using Lora. 

Any ideas about the issue? Is it because the arguments of my lora training command are given wrong? 
Looking forward to your reply as we are preparing to submit a paper. Thanks so much!

**Comment by caradryanl** [comment]
Had been responsed through other approaches.

**Comment by lunaryan** [comment]
It turns out you should specify lora_weight.pt/safefactors within the LORA_OUTPUT_DIR
