### ISSUE TITLE
GUI Feedback & Ending Process

### ISSUE THREAD

**Issue by ndo360** [mist-project/mist-v2#23]
Greetings!

I love the most recent update that supports a one click setup. I believe the GUI for Mist v2 needs to be updated to give feedback for users to know that their images are being Misted. (I am aware that the CMD prompt updates, but it doesn't go to the forefront after the 'Mist' button is pressed)

I think that the best setup would be to have a debug box within the GUI, underneath the MIST button, that echos what the command line is saying in the background. That way there is feedback for the client running the program.

Secondly I believe that the command line should make it clear it is ready to mist again. Currently it lists, when the process is fully finished, that the images have been exported... then it just hangs there. It leaves me unsure if it's still running in the background stuck, or if it was just finished and is idling. I am aware that one could close the window, but in doing so would kill the entire process and require a re-run.

My solution is that once it's done, presuming that it is idling doing nothing and not consuming resources, is that it echos a comment for the end-user that the requested images have been misted and the program is ready to mist another batch if desired. Something like:

"X images successfully Misted!"

This could be implemented in the GUI itself by having the "Mist button" change colors, and show a revolving circle as its doing the process, and switch back to its normal state once done with a small pop-up window declaring the Misting completed successfully. 

Thanks again for your amazing work.

**Comment by caradryanl** [comment]
Hi! Thank you for your advice. I think these ideas are quite straight-forward but useful for improving our user experience. We will soon have them updated.
