### ISSUE TITLE
error wont work? (idk what this means)

### ISSUE THREAD

**Issue by random-egg** [mist-project/mist-v2#24]
![Screenshot (211)](https://github.com/psyker-team/mist-v2/assets/167741945/90fd5222-7adb-4ed6-b166-7cdee5447d64)
![Screenshot (212)](https://github.com/psyker-team/mist-v2/assets/167741945/5d184a1b-c675-475b-a3e1-9fa2beaab26f)

**Comment by ghost** [comment]
You have failed to install all the required packages. Please confirm whether you have followed the instructions.
