### ISSUE TITLE
Generating class images stuck at 0%

### ISSUE THREAD

**Issue by jhaunn** [mist-project/mist-v2#26]
I've successfully cloned the repository and run the commands required to install the environment for mist; I've also added stable-diffusion-1-5 in the root folder, as it was not included in the repository. However, once I ran mist-v2 in the default CPU setup, the generation of class images was stuck at 0%. I've also tried running it in the default GPU setup, but it said that my GPU does not meet the requirements. Any fix?

![error](https://github.com/psyker-team/mist-v2/assets/89385585/4c41766e-6f26-46d6-aaaa-0be97a4d7bd0)

**Comment by caradryanl** [comment]
Responded in other issues.

**Comment by jhaunn** [comment]
> Responded in other issues.

I can't seem to find the issue you're referring to. Would it be possible to send the link?

**Comment by caradryanl** [comment]
Sorry for misleading. This is because CPU is not well supported currently. You may need a GPU with met requirements to run it. For the requirement see 

![image](https://github.com/user-attachments/assets/31959176-074a-4fb5-8da2-cea35943b32b)
