### ISSUE TITLE
PGD Attack stuck at 0%

### ISSUE THREAD

**Issue by jhaunn** [mist-project/mist-v2#27]
I'm running mist via mist GUI booter, and I encountered an error where the PGD Attack is stuck at 0%. I didn't change the source code or configure anything in the professional setup. Does anyone have a fix for this? 
![mist-error](https://github.com/psyker-team/mist-v2/assets/89385585/b2df88c9-e3d1-44c3-8638-a2c8131ff9f1)

Here is the setup I used; I used the CPU setup since I tried using GPU setup, but it said that my GPU does not meet the requirement / not available
![setup](https://github.com/psyker-team/mist-v2/assets/89385585/53295889-5354-45f0-b575-86716c4fad22)

**Comment by caradryanl** [comment]
CPU running could be extremely slow now. I am trying to optimize it.
