### ISSUE TITLE
Hope to get a version deployed with Docker

### ISSUE THREAD

**Issue by kinoward** [mist-project/mist-v2#9]
Hope to get a version deployed with Docker. Thank you~

**Comment by caradryanl** [comment]
Thank you for your attention! Currently we have too much to do about the accessibility of mist-v2 as well as its academic publishment so docker deployment are not on the top of our TODO list. But we sincerely welcome any tries to have Mist-v2 deployed with Docker. If you are willing to do this, you can directly contact us through our mail: mist202304@gmail.com.
